extract linux playback to function

diff --git a/notify-if-background b/notify-if-background
--- a/notify-if-background
+++ b/notify-if-background
@@ -172,12 +172,24 @@
         function notifier-linux {
             notify-send "$notification_title" "$message"
 
+            function play-sound {
+              if which paplay > /dev/null 2>&1; then
+                paplay "$1"
+              elif which aplay > /dev/null 2>&1; then
+                aplay "$1"
+              elif which ossplay > /dev/null 2>&1; then
+                ossplay "$1"
+              else
+                echo "Could not find a sound file player." >&2
+                return 1
+              fi
+            }
+
             if [[ ! -z "$notification_sound" ]]; then
-                if [[ -a $notification_sound ]]; then
-                    local player=`(which paplay || which aplay || which ossplay) | tail -n 1`
-                    eval $player $notification_sound
+                if [[ -a "$notification_sound" ]]; then
+                    play-sound "$notification_sound"
                 else
-                    echo "zsh-notify: file $notification_sound not found."
+                    echo "File $notification_sound not found." >&2
                 fi
             fi
 
